#!/bin/bash


#User Input
CH=""


show_options () {
        CH=$(whiptail --title "Users" --menu "List Users" 25 78 16 \
        "Ordinary" "List Ordinary Users (uid =>1000)" \
        "System"   "List System Users (uid <1000)" \
        "All"      "List All Users" \
        3>&1 1>&2 2>&3)

	#If the user pressed cancel, terminate, otherwise go on
        if [ "$?" != 0 ]; then
                exit
        fi
}


show_system_users () {

	#UIDs end with three digits or less (less than 1000)
	whiptail --title "System Users" --yesno \
	"$(cut /etc/passwd -d : -f 1,3 --output-delimiter=" ==> " | grep -E "[^0-9][0-9?][0-9?][0-9]$")" \
	--scrolltext --yes-button "ok" --no-button "cancel" 20 78

	if [ "$?" != 0 ]; then
		show_options
	else
		exit
	fi
}

show_ordinary_users () {

        #UIDs end with 4 digits or more(less than 1000)
        whiptail --title "Ordinary Users" --yesno \
        "$(cut /etc/passwd -d : -f 1,3 --output-delimiter=" ==> " | grep "[0-9][0-9][0-9][0-9]")" \
	--yes-button "ok" --no-button "cancel" --scrolltext 20 78

	if [ "$?" != 0 ]; then
                show_options
        else
                exit
        fi
}

show_all_users () {

	whiptail --title "All Users" --yesno \
        "$(cut -d : -f 1,3 --output-delimiter=" ==> " /etc/passwd)" --scrolltext \
	--yes-button "ok" --no-button "cancel" --scrolltext 20 78

        if [ "$?" != 0 ]; then
                show_options
        else
            	exit
        fi
}

show_options

#Infinite loop, exiting is handled inside show functions
while [ 0 -eq 0 ]
	do

		case "$CH" in
			"Ordinary")
			show_ordinary_users
			;;

			"System")
			show_system_users
			;;

			"All")
			show_all_users
			;;

			*)
			exit
			;;
		esac
done
